# Use the Nginx image
FROM nginx

# Remove the default nginx.conf
RUN rm /etc/nginx/conf.d/default.conf

# Replace with our own nginx.conf
# COPY nginx.conf /etc/nginx/conf.d/
# COPY cert.pem /etc/ssl/
# COPY privkey.pem /etc/ssl/
# COPY fullchain.pem /etc/ssl/
# COPY options-ssl-nginx.conf /etc/ssl
# COPY ssl-dhparams.pem /etc/ssl

