version: "3.7"


services:
  auth-service-db:
    container_name: 'auth-service-db'
    image: postgres
    volumes:
      - ./data/authentication_db:/data/postgres
    ports:
      - "9008:5432"
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - PGDATA=/data/postgres

  auth-service:
    build: ./auth
    container_name: 'auth-service'
    env_file:
      - auth/.env
    command: uwsgi --http :8000 --module auth.wsgi
    ports:
      - '8000:8000'

  krakend:
    build: ./krakend/gateway
    container_name: krakend
    restart: always
    expose:
      - 8080
    depends_on:
      - authentication_flask
      - authentication_nginx
    links:
      - authentication_nginx
      - cashflow_nginx
      - dealsncustomers_nginx
      - designing_nginx

  krakend_nginx:
    build: ./krakend/nginx
    container_name: krakend_nginx
    restart: always
    depends_on:
      - krakend
    ports:
      - "80:80"


volumes:
  authentication_db: