version: "3.7"


services:
  auth-service-db:
    container_name: 'auth-service-db'
    image: postgres
    volumes:
      - ./data/authentication_db:/var/lib/postgresql/data
    ports:
      - "9008:5432"
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
  auth-service:
    build: ./chat
    container_name: 'auth-service'
    env_file:
      - chat/.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    ports:
      - '8000:8000'
