# Generated by Django 4.2.1 on 2024-03-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='date_of_end',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='date_of_start',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='RestaurantPlanMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField(null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.dishtype'),
        ),
    ]
