# Generated by Django 4.2.1 on 2024-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_dish_menu_menu_dishes_alter_dish_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date_of_open',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
