# Generated by Django 4.2.1 on 2024-03-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_restaurant_date_of_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date_of_open',
            field=models.DateField(null=True),
        ),
    ]
