# Generated by Django 4.2.1 on 2024-03-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_restaurant_date_of_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantplanmenu',
            name='datetime_end',
        ),
        migrations.RemoveField(
            model_name='restaurantplanmenu',
            name='datetime_start',
        ),
        migrations.AddField(
            model_name='restaurantplanmenu',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='restaurantplanmenu',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
