# Generated by Django 4.2.1 on 2024-04-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_restaurantplanmenu_datetime_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=50.0, max_digits=9),
            preserve_default=False,
        ),
    ]
