# Generated by Django 4.2.1 on 2024-04-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_restaurant_latitude_alter_restaurant_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantplanmenu',
            name='date_start',
            field=models.DateField(),
        ),
    ]
