# Generated by Django 4.2.1 on 2024-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_restaurantplanmenu_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.DeleteModel(
            name='MobilePhoneModel',
        ),
        migrations.DeleteModel(
            name='PhoneBlackList',
        ),
        migrations.DeleteModel(
            name='TableReservation',
        ),
    ]
