# Generated by Django 4.2.1 on 2024-04-10 14:42

import apps.food.services.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_remove_phoneblacklist_blocking_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('patronymic', models.CharField(max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=30, unique=True, validators=[apps.food.services.validators.validate_phone_number])),
            ],
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('time_of_start', models.DateTimeField()),
                ('time_of_end', models.DateTimeField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('has_come', models.BooleanField(default=False)),
                ('number_of_people', models.IntegerField(default=1)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.dish')),
                ('stage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='food.orderstage')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.dish')),
                ('dishes', models.ManyToManyField(to='food.orderdish')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.client')),
            ],
        ),
    ]
