# Generated by Django 4.2.1 on 2024-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_remove_order_dishes_orderdish_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(through='food.OrderDish', to='food.dish'),
        ),
    ]
