# Generated by Django 4.2.1 on 2024-04-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdish',
            name='stage',
            field=models.CharField(choices=[('not ready', 'not ready'), ('ready', 'ready')], default='not ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('not ready', 'not ready'), ('ready', 'ready')], default='not ready', max_length=256),
        ),
        migrations.DeleteModel(
            name='OrderStage',
        ),
    ]
