# Generated by Django 4.2.1 on 2024-04-21 20:27

import apps.food.services.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_orderdish_stage_alter_order_stage_delete_orderstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[apps.food.services.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='clientblacklist',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('not ready', 'not ready'), ('ready', 'ready'), ('finished', 'finished')], default='not ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='stage',
            field=models.CharField(choices=[('not ready', 'not ready'), ('ready', 'ready'), ('finished', 'finished')], default='not ready', max_length=256),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.table'),
            preserve_default=False,
        ),
    ]
